@startuml


title UML Sequence Diagram for Profile Creation
participant Main
participant "profile:Profile" AS profile
participant "newProfile:Profile" AS newProfile
-> Main ++ : checkAndCreateProfile()
Main -> profile ++ : profile.checkProfileComplete()
alt true
profile --> Main --  : return
note right: no changes to profile
else
profile -> profile ++ : profile.checkProfilePresent()
alt true
profile --> Main ++  :repairProfile()
Main --> Main -- : return
note right : changes are directly made to the profile
else
profile --> Main ++ : createNewProfile()
create newProfile
Main -> newProfile ++ : new Profile()
newProfile --> profile -- : return
note right : profile in main is \n replaced by newProfile
profile -> Main -- : return
Main --> Main -- : exits createNewProfile()
end
end
<-- Main -- : exits checkAndCreateProfile()




@enduml