@startuml
'https://plantuml.com/sequence-diagram

!include Style.puml
hide footbox

participant "command:AddFoodCommand" As AddFoodCommand LOGIC_COLOUR
participant "foodBank:FoodBank" As FoodBank DATA_COLOUR

?->AddFoodCommand :execute()
activate AddFoodCommand LOGIC_COLOUR

opt isCalorieFromFoodBank
    AddFoodCommand -> FoodBank : findCalorie(description)
    activate FoodBank DATA_COLOUR
    FoodBank --> AddFoodCommand : calories
    deactivate FoodBank
end

create "food" As Food DATA_COLOUR
AddFoodCommand -> Food ** : new Food(description,calories,dateTime)
activate Food DATA_COLOUR
Food -> Food ++ DATA_COLOUR : setTimePeriod (dateTime)
Food --> Food --
Food --> AddFoodCommand : food
deactivate Food

participant "filteredFoodList:FoodList" As FoodList DATA_COLOUR
participant "commandResult:CommandResult" As CommandResult LOGIC_COLOUR
AddFoodCommand -> FoodList : \t\t\t\t\t\t\t\t\taddItem(food)
activate FoodList DATA_COLOUR
FoodList -> FoodList ++  DATA_COLOUR: sortList()
FoodList --> FoodList --
FoodList --> AddFoodCommand
deactivate FoodList
AddFoodCommand -> CommandResult **: \tnew CommandResult(String.format(MESSAGE_SUCCESS,food))
activate CommandResult LOGIC_COLOUR
CommandResult --> AddFoodCommand
deactivate CommandResult

?<-- AddFoodCommand : commandResult\t
deactivate AddFoodCommand
destroy Food
destroy CommandResult
destroy AddFoodCommand
@enduml