@startuml
'https://plantuml.com/sequence-diagram
hide footbox
!include Style.puml
participant ":StartState" As StartState STATE_COLOUR
-> StartState ++ STATE_COLOUR: checkAndCreateProfile()
participant "oldProfile:Profile" as oldProfile DATA_COLOUR
StartState -> oldProfile ++ DATA_COLOUR :checkProfileComplete()
oldProfile --> StartState --
alt profile.checkProfileComplete()
else
StartState -> StartState ++ STATE_COLOUR: createProfile()
participant "newProfile:Profile" as newProfile DATA_COLOUR
create newProfile
StartState ->newProfile ++ DATA_COLOUR : new Profile()
loop !profile.checkProfileComplete
ref over StartState,newProfile
create Profile attributes
end
end
newProfile --> StartState --
participant ":StorageManager" as StoreManager STORAGE_COLOUR
StartState -> StoreManager ++ STORAGE_COLOUR: saveProfile(profile)
StoreManager --> StartState --
StartState --> StartState -- MAIN_COLOUR : replace profile
end
<-- StartState -- : profile
destroy oldProfile



@enduml