@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
hide footbox

group sd Decode Name
participant ":ProfileDecoder" As ProfileDecoder STORAGE_COLOUR
participant ":Name" As Name DATA_COLOUR

activate ProfileDecoder STORAGE_COLOUR
ProfileDecoder -> Name ** DATA_COLOUR: new Name(detail)
activate Name DATA_COLOUR
    Name --> ProfileDecoder
deactivate
destroy Name
end
@enduml