@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
hide footbox

group sd Decode CalorieGoal
participant ":ProfileDecoder" As ProfileDecoder STORAGE_COLOUR
participant ":CalorieGoal" As CalorieGoal DATA_COLOUR

activate ProfileDecoder STORAGE_COLOUR
alt no errors thrown
ProfileDecoder -> CalorieGoal ** DATA_COLOUR: new CalorieGoal(Integer.parse(detail))
activate CalorieGoal DATA_COLOUR
    CalorieGoal --> ProfileDecoder
deactivate
destroy CalorieGoal
else NumberFormatException
ProfileDecoder -> CalorieGoal ** DATA_COLOUR: new CalorieGoal(Integer.MIN_VALUE)
note right STORAGE_FADED_COLOUR
 The (Integer.MIN_VALUE) here represents an invalid integer
 of CalorieGoal that is handled later on in the startup of
 the bot.
end note
activate CalorieGoal DATA_COLOUR
    CalorieGoal --> ProfileDecoder
deactivate
destroy CalorieGoal

end

end
@enduml