@startuml
'https://plantuml.com/class-diagram
!include Style.puml
hide circle
hide methods

class ItemBank DATA_COLOUR
class "{abstract}\nItemList" as ItemList DATA_COLOUR
class FoodList DATA_COLOUR
class ExerciseList DATA_COLOUR
class FutureExerciseList DATA_COLOUR

ItemBank <|-down- ItemList
ItemList <|-down- FoodList
ItemList <|-down- ExerciseList
ExerciseList <|-down- FutureExerciseList

class "{abstract}\nItem" as Item DATA_COLOUR{
#name: String
#calories: int
}

class Food DATA_COLOUR {
#dateTime: LocalDateTime
}

class Exercise DATA_COLOUR {
#date: LocalDate
}

enum "<<enumeration>>\nTimePeriod" as TimePeriod DATA_COLOUR {
Morning, Afternoon,
Evening, Night
}

Item <|-down- Food
Item <|-down- Exercise
Item "*" <-left- ItemBank: internalItems
TimePeriod "1" <-- Food : timePeriod\n\n
Item <.. ItemList
Item <.. FoodList
Item <.. ExerciseList
Food <.. FoodList
Exercise <.. ExerciseList
Exercise <.. FutureExerciseList
note "Class methods are not shown for simplicity" as N1 DATA_COLOUR
@enduml