@startuml
skinparam BackgroundColor white
skinparam componentStyle rectangle
component  {
   component "Main"
   component Logic
   component Ui
   component Data
   component Storage

}
[user]->[Ui]
[Ui] -> [Main]
[Main] -> [Logic]
[Main] -> [Data]
[Logic] -> [Data]
[Main] -> Storage
@enduml