@startuml
'https://plantuml.com/class-diagram

!include Style.puml
hide class fields
hide class methods
hide interface fields
hide interface methods

class ProfileDecoder STORAGE_COLOUR
class ProfileStorage STORAGE_COLOUR
class "{abstract}\nStorage" STORAGE_COLOUR
class ProfileEncoder STORAGE_COLOUR
interface "<<interface>>\nProfileStorageInterface" STORAGE_COLOUR

"{abstract}\nStorage" <|-down- ProfileStorage
"<<interface>>\nProfileStorageInterface" <|.left. ProfileStorage
ProfileDecoder .up.> ProfileStorage
ProfileEncoder .up.> ProfileStorage

@enduml