@startuml

!include Style.puml
hide circle
hide empty members
skinparam minclassWidth 120
skinparam Padding 5

class AttributeCreator MAIN_COLOUR
class NameCreator MAIN_COLOUR
class HeightCreator MAIN_COLOUR
class WeightCreator MAIN_COLOUR
class GenderCreator MAIN_COLOUR
class AgeCreator MAIN_COLOUR
class CalorieGoalCreator MAIN_COLOUR
class ActivityFactorCreator MAIN_COLOUR
class StartState MAIN_COLOUR


StartState ..> NameCreator : > executes
StartState ..> HeightCreator : > executes
StartState ..> WeightCreator : > executes
StartState ..> GenderCreator : > executes
StartState ..> AgeCreator : > executes
StartState ..> CalorieGoalCreator : > executes
StartState ..> ActivityFactorCreator : > executes
NameCreator --|> AttributeCreator
HeightCreator --|> AttributeCreator
WeightCreator --|> AttributeCreator
GenderCreator --|> AttributeCreator
AgeCreator --|> AttributeCreator
CalorieGoalCreator --|> AttributeCreator
ActivityFactorCreator --|> AttributeCreator



@enduml