@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
hide footbox

participant "profileStorage:ProfileStorage" As ProfileStorage STORAGE_COLOUR
participant ":ProfileDecoder" As ProfileDecoder STORAGE_COLOUR

participant "file:File" As File STORAGE_COLOUR
participant "in:Scanner" As Scanner STORAGE_COLOUR
participant "profile:Profile" As Profile DATA_COLOUR
participant ":Profile" As Profile2 DATA_COLOUR

ProfileStorage -> ProfileDecoder: retrieveProfileFromData(filePath)
activate ProfileDecoder STORAGE_COLOUR
    ProfileDecoder -> File **: new File(filePath)
    activate File STORAGE_COLOUR
        File --> ProfileDecoder: file
    deactivate
    ProfileDecoder -> Scanner ** : new Scanner(file)
    activate Scanner STORAGE_COLOUR
        Scanner --> ProfileDecoder:
    deactivate
    ProfileDecoder -> ProfileDecoder ++ STORAGE_COLOUR: decodeProfile
    alt in.hasNext
        ProfileDecoder -> Scanner : nextLine()
        activate Scanner STORAGE_COLOUR
            Scanner --> ProfileDecoder: line
        deactivate
        ProfileDecoder -> ProfileDecoder ++ STORAGE_COLOUR: decodeProfileDataFromString(line)
        ProfileDecoder -> Profile ** : new Profile()
        activate Profile DATA_COLOUR
            Profile --> ProfileDecoder : profile
        deactivate
        ProfileDecoder -> Profile: setProfileWithRawInputs(name, ...)
        activate Profile DATA_COLOUR
            Profile --> ProfileDecoder :
        deactivate
        ProfileDecoder --> ProfileDecoder -- : profile
        destroy Profile
    else else
        ProfileDecoder -> Profile2 ** : new Profile()
        activate Profile2 DATA_COLOUR
            Profile2 --> ProfileDecoder : profile
        deactivate
        destroy Profile2
    end
    ProfileDecoder --> ProfileDecoder -- : profile
    destroy Scanner
    destroy File
    ProfileDecoder --> ProfileStorage : profile
deactivate

@enduml