@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
hide footbox
actor User
participant Ui
participant Main
User -> Ui ++ : getInput()
Ui -> Main ++ : "performs commands"
Main --> Ui -- : formatMessageWithFramedDivider()
Ui --> User --
@enduml